version: '3'

services:

  web:
    image: rubinus/mygo
    volumes:
      - "/Users/rubinus/go/src/mygo:/go/src/mygo"
    environment:
      REDIS_HOST: redis
      MONGO_HOST: mongo
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
    ports:
      - 16379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock