version: '3'

services:

  web:
    image: rubinus/mygo
    environment:
      REDIS_HOST: redis
      MONGO_HOST: mongo
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
    ports:
      - 16379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017