version: '3'

services:

  web:
    image: rubinus/mygo
    environment:
      REDIS_HOST_PORT: redis
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 16379:6379
  mongodb:
    image: mongodb
    ports:
      - 27017:27017