version: '3.3'
services:
  shard1_1:
    image: mongo
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard1:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        # 指定在服务器 VM_50_201_centos 上启动
        constraints:
          - node.hostname==VM_50_201_centos
  shard2_1:
    image: mongo
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard2:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_50_201_centos
  shard3_1:
    image: mongo
    command: mongod --shardsvr --replSet shard3 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard3:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_50_201_centos
  shard1_2:
    image: mongo
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard1:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_219_143_centos
  shard2_2:
    image: mongo
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard2:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_219_143_centos
  shard3_2:
    image: mongo
    command: mongod --shardsvr --replSet shard3 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard3:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_219_143_centos
  shard1_3:
    image: mongo
    command: mongod --shardsvr --replSet shard1 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard1:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_233_170_centos
  shard2_3:
    image: mongo
    command: mongod --shardsvr --replSet shard2 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard2:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_233_170_centos
  shard3_3:
    image: mongo
    command: mongod --shardsvr --replSet shard3 --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/shard3:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_233_170_centos
  cfg_1:
    image: mongo
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/configsvr:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_50_201_centos
  cfg_2:
    image: mongo
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/configsvr:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_219_143_centos
  cfg_3:
    image: mongo
    command: mongod --configsvr --replSet cfg --dbpath /data/db --port 27017
    networks:
      - mongo-nw
    volumes:
      - /opt/mongo-cluster-swarm/configsvr:/data/db
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_233_170_centos
  mongos:
    image: mongo
    # mongo 3.6 版默认绑定IP为 127.0.0.1，此处绑定 0.0.0.0 是允许其他容器或主机可以访问
    command: mongos --configdb cfg/cfg_1:27017,cfg_2:27017,cfg_3:27017 --bind_ip 0.0.0.0 --port 27017
    networks:
      - mongo-nw
    # 映射宿主机的 27000 端口
    ports:
      - 22000:27017
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - cfg_1
      - cfg_2
      - cfg_3
    deploy:
      restart_policy:
        condition: on-failure
      # 在集群内的每一台服务器上都启动一个容器
      mode: global
networks:
  mongo-nw:
    external: true