version: '3.3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4161:4161"
      - "4160:4160"
    networks:
      - nsq-nw
    hostname: nsqlookupd
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.hostname==VM_50_201_centos
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "4171:4171"
    networks:
      - nsq-nw
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
  nsqd:
      image: nsqio/nsq
      command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data
      depends_on:
        - nsqlookupd
      ports:
        - "4151:4151"
        - "4150:4150"
      networks:
        - nsq-nw
      hostname: nsqd
      volumes:
        - /opt/nsq-cluster-swarm:/data
        - /etc/localtime:/etc/localtime
      deploy:
        restart_policy:
          condition: on-failure
        replicas: 1
        placement:
          constraints:
            - node.hostname==VM_219_143_centos
networks:
  nsq-nw:
    external: true